### ISSUE TITLE
streamline getting access token

### ISSUE THREAD

**Issue by JLessinger** [JLessinger/fb_prune#6]
currently need to do it manually from graph explorer web interface

possible alternative: Facebook Login API
- does this grant enough permission?

**Comment by eccentricayman** [comment]
I thnik the login API needs it to be a registered Facebook app, and the app needs to be reviewed. It should be able to grant enough permission though.

**Comment by JLessinger** [comment]
Right, ok. I don't see a way to guarantee app integrity to users then, so we'll use the Graph Explorer to get access tokens as planned.

**Comment by JLessinger** [comment]
Actually, maybe it's possible, but it's convoluted:

If Facebook publishes callback URLs, then we could host it somewhere publicly readable. The challenge would be to keep the secret key hidden but the rest of the code public while guaranteeing that nothing else is hidden. We would also have to exclude the key from the checksum.

Thoughts, anyone?

**Comment by veeara282** [comment]
We could write the login code in JavaScript using the Facebook SDK and run it through [PyExecJS](https://pypi.python.org/pypi/PyExecJS) or a similar engine.

**Comment by veeara282** [comment]
We could also just make this a registered Facebook app with a web interface. I have a blank one sitting around from last week's hackathon.

**Comment by JLessinger** [comment]
Your first suggestion gives us the convenience of fb login and the security guarantee of having a native desktop app. I think we should try that.
https://developers.facebook.com/docs/facebook-login/manually-build-a-login-flow

**Comment by veeara282** [comment]
When I use `execjs.eval()`, I get this error:

```
Traceback (most recent call last):
  File "login.py", line 29, in <module>
    vm.eval(f.read())
  File "/usr/local/lib/python2.7/dist-packages/execjs/_abstract_runtime_context.py", line 27, in eval
    return self._eval(source)
  File "/usr/local/lib/python2.7/dist-packages/execjs/_external_runtime.py", line 71, in _eval
    return self.exec_(code)
  File "/usr/local/lib/python2.7/dist-packages/execjs/_abstract_runtime_context.py", line 18, in exec_
    return self._exec_(source)
  File "/usr/local/lib/python2.7/dist-packages/execjs/_external_runtime.py", line 82, in _exec_
    output = self._execfile(filename)
  File "/usr/local/lib/python2.7/dist-packages/execjs/_external_runtime.py", line 106, in _execfile
    raise exceptions.RuntimeError("stdout: {}, stderr: {}".format(repr(stdoutdata), repr(stderrdata)))
execjs._exceptions.RuntimeError: stdout: '', stderr: ''
```

I don't know what's going on. My last two or so commits to the branch `access-token` show everything I've tried.

**Comment by JLessinger** [comment]
What about making a simple web interface as described here https://developers.facebook.com/docs/facebook-login/web

I created an app and edited your script to write an html file that loads the js sdk.
run $ python login.py app-id sdk2.html
to create sdk2.html with the app id plugged in. then just open sdk2.html in a browser. In chrome, if you go to the javascript console, you can see the FB object initialized.

check slack for the app id.

Also check this out https://developers.facebook.com/docs/php/howto/example_access_token_from_javascript

When you want to log a user in, you do it on the server side providing FB with the app secret. That makes sense to me. What I don't understand is why FB doesn't authenticate the app when you first load the SDK.

**Comment by JLessinger** [comment]
Actually, there's still a problem. We'd have to distribute the app secret to users. Which makes me wonder how this is done for native apps (which they claim is possible).

Let's table this for now and just get access tokens manually.
